apiVersion: v1
kind: Service
metadata:
  name: application
  labels:
    app: libvirtd
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: libvirtd
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: libvirtd-client
  labels:
    app: libvirtd
spec:
  ports:
  - port: 16509
    name: client-connection
  - port: 5900
    name: spice
  - port: 22
    name: ssh
  selector:
    app: libvirtd
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: libvirtd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: libvirtd
    spec:
      containers:
      - image: docker.io/sebassch/mylibvirtd:devel
        imagePullPolicy: Always
        name: compute
        ports:
        - containerPort: 9080
        - containerPort: 16509
        - containerPort: 5900
        - containerPort: 22
        securityContext:
          capabilities:
            add:
            - ALL
          privileged: true
          runAsUser: 0
        volumeMounts:
          - mountPath: /var/lib/libvirt/images
            name: test-volume
          - mountPath: /host-dev
            name: host-dev
          - mountPath: /host-sys
            name: host-sys
        resources: {}
        env:
          - name: LIBVIRTD_DEFAULT_NETWORK_DEVICE
            value: "eth0"
      volumes:
      - name: host-dev
        hostPath:
          path: /dev
          type: Directory
      - name: host-sys
        hostPath:
          path: /sys
          type: Directory
      - name: test-volume
        hostPath:
          path: /bricks/brick1/volume/Images
          type: Directory
status: {}
